### ISSUE TITLE
Comercial - Dispel

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#10]
Se debe cotizar:

- Cambio de Tarjeta de Red PCI equipo compaq Pentium IV 
- Cambio de Sistema Operativo de Windows XP a Windows 7 (No Licenciado)
- Inventario Hardware y Software
- Cotizar Antivirus para 7 equipos
- Mantenimiento correctivo 7 equipos (software no limpieza)

**Comment by Bibianarosas** [comment]
Propuesta Enviada en espera de desicion
