### ISSUE TITLE
VELUQUE - SERVIDOR

### ISSUE THREAD

**Issue by sebastiandelgadopc** [soportepctecnologia/PCTecnologiaSAS#101]
Ingresa temporalmente servidor de veluque para conexion remota desde la oficina mientras se ajusta el servicio de internet.

Se configuran los parametros IP de la siguiente manera:

192.168.1.53
255.255.255
192.168.1.1

NAT 181.55.254.65:1706 para conectar al servidor

**Comment by dsoportepc** [comment]
14/01/2019
Se realizara entrega de servidor a la compañia se da salida del equipo con los siguientes elementos:
-Disco duro de backups
-Cable de poder
-Cable de red
-Su respectiva llave 
El equipo sera entregado por el Ingeniero Hassan el dia de hoy

**Comment by juancamilopc** [comment]
se realiza mesa de ayuda para el remoto del servidor, ya que los clientes de veluque no podian ingresar en el momento, porque la direccion ip era muy inestable, se procede a cambiar la ip asignada al servidor por una estable y se cambia en el remoto de cada equipo de veluque para que ingrese de manera correcta y sin inconvenientes.

![WhatsApp Image 2019-09-03 at 11 07 47 AM](https://user-images.githubusercontent.com/54682487/64211666-7ff40880-ce6c-11e9-9940-4cc85a353360.jpeg)
![WhatsApp Image 2019-09-03 at 10 49 07 AM](https://user-images.githubusercontent.com/54682487/64211667-7ff40880-ce6c-11e9-8b2c-2a0c6fb10e0e.jpeg)

**Comment by juancamilopc** [comment]
se realiza mesa de ayuda para el remoto del servidor, ya que los clientes de veluque no podian ingresar en el momento, porque la direccion ip era muy inestable, se procede a cambiar la ip asignada al servidor por una estable y se cambia en el remoto de cada equipo de veluque para que ingrese de manera correcta y sin inconvenientes.

![WhatsApp Image 2019-09-03 at 11 07 47 AM](https://user-images.githubusercontent.com/54682487/64211666-7ff40880-ce6c-11e9-9940-4cc85a353360.jpeg)
![WhatsApp Image 2019-09-03 at 10 49 07 AM](https://user-images.githubusercontent.com/54682487/64211667-7ff40880-ce6c-11e9-8b2c-2a0c6fb10e0e.jpeg)
