### ISSUE TITLE
Leonardo Ortiz - Laboratorio

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#102]
Ingresa equipo para reinstalacion de sistema y copia de seguridad de la informacion en disco duro extraible. Instalar el sistema con el office home and studen con licencia original.

**Comment by hsoporte** [comment]
Se reinstalo el equipo con recovery y el office home and student con licencia original, se instalaron los programas pertinentes y Kaspersky small and bussiness, esta pendiente por activar la licencia de antivirus mientras la confirman, unicamente es necesario activar la licencia para entregar el equipo.

**Comment by dsoportepc** [comment]
Equipo entregado correctamente.
