### ISSUE TITLE
PRADA - LABORATORIO

### ISSUE THREAD

**Issue by sebastiandelgadopc** [soportepctecnologia/PCTecnologiaSAS#103]
El usuario manifiesta que el equipo no enciende.
24/09/2018: Se revisa el equipo, si enciende, presenta fallas de arranque del sistema operativo.

**Comment by jsoporte** [comment]
25/09/2018: Se realizo backup de información, se procede a instalar sistema operativo windows 7 x64.

**Comment by dsoportepc** [comment]
Equipo entregado. Caso cerrado
