### ISSUE TITLE
VELUQUE - BARANQUILLA

### ISSUE THREAD

**Issue by jsoporte** [soportepctecnologia/PCTecnologiaSAS#104]
25/09/2018: El equipo presenta problemas de disco duro y el sistema operativo no carga, se queda en el logo de windows.
26/09/2018: Se realizo el cambio del disco duro, por uno nuevo de la misma capacidad 500GB y se instalo el sistema operativo windows 8.1.
27/09/2018: Se le instalaron las actualizaciones del sistema operativo, generando unas de estas no detectadas, fallas de funcionamiento en el equipo, por lo que fue necesario ejecutar un punto de restauración de un día anterior.
28/09/2018: El sistema operativo sigue presentando molestias, por lo que se determino a realizar la reinstalacion del sistema operativo.

**Comment by dsoportepc** [comment]
Equipo entregado
