### ISSUE TITLE
MORENOS PORTOS - Equipo SENA

### ISSUE THREAD

**Issue by jsoporte** [soportepctecnologia/PCTecnologiaSAS#105]
03/10/2018: Se realizo backup de información por solicitud de la señora Josefina, para realizar formateo del equipo, por in-eficiencia en el rendimiento. 
04/10/2018: Se realizo el formateo del equipo, se detecto que presenta una falla en el disco duro por lo que se requiere el cambio del mismo.
05/10/2018: Se realizo la limpieza de hardware soplando sus componentes internos, se retiro el disco defectuoso y se instalo un disco nuevo de 500GB capacidad, se procedió a instalar el sistema operativo, realizar activación y actualización.  
08/10/2018: se entrego en las instalaciones, se agrego al dominio, se le instalo el backup, progrmas y actualizaciones del sistema operativo.

**Comment by dsoportepc** [comment]
Equipo entregado
