### ISSUE TITLE
OVERHAUL SERVICES - CAMBIO DE PANTALLA

### ISSUE THREAD

**Issue by jsoporte** [soportepctecnologia/PCTecnologiaSAS#106]
SAMSUNG N145 Plus S/N:HLV293LBC00373Y
12/10/2018: El equipo ingresa para cambio de pantalla.
13/10/2018: Se realizo el cambio de pantalla del equipo, queda funcionando sin

**Comment by dsoportepc** [comment]
Equipo entregado
