### ISSUE TITLE
ALIRIO RINCON - EQUIPO NO ENCIENDE

### ISSUE THREAD

**Issue by jsoporte** [soportepctecnologia/PCTecnologiaSAS#107]
TOSHIBA SATELLITE C645D-SP4010L   S/N:YA457464Q
12/10/2018: El equipo ingreso al laboratorio, se realizaron las pruebas respectivas:
DIAGNOSTICO:
El equipo enciende pero no muestra video, para descartar fallas se realizaron las siguientes pruebas:
- Se probo memoria RAM, retirándola y haciendo limpieza de contactos y slock de memoria.
- Se probo vídeo por puerto VGA, con monitor externo.
- Se retiro pila de board
A pesar de las pruebas ninguna genero resultado positivo por lo que es necesario realizar reflow de GPU.
Observaciones: El equipo queda desarmado. 
03/10/2018:
Se realizo reflow, el equipo dio vídeo.
Se realizo mantenimiento preventivo del equipo, eliminación de temporales.

**Comment by dsoportepc** [comment]
El equipo se encuentra listo para entregar, se intenta contactar al señor Alirio Rincon pero no contesta.

**Comment by hsoporte** [comment]
Pendiente que el cliente recoja el equipo
