### ISSUE TITLE
MORENOS - EQUIPO ANALISTA COMERCIAL

### ISSUE THREAD

**Issue by jsoporte** [soportepctecnologia/PCTecnologiaSAS#108]
HP pro one 400 G2-20 Roberto Aranda 
13/10/2018: El equipo ingresa a laboratorio con falla al cargar el sistema operativo, se procede a realizar restauración del sistema desde el Recovery.

**Comment by dsoportepc** [comment]
El equipo fue entregado por el ingeniero David Jesus Gonzales,
