### ISSUE TITLE
Laboratorio - Dispel

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#11]
Revision Monitor LG, se prende y da video 2 segundos y luego se apaga

**Comment by jennifervargas** [comment]
Rafael Campo se lo lleva para hacerle pruebas en su laboratorio

**Comment by jennifervargas** [comment]
Se determina que se deben cambiar dos lamparas a la pantalla, entra en proceso de autorización por parte del cliente

**Comment by jennifervargas** [comment]
El cliente no autoriza el cambio de las lamparas, se recomiendo a Rafael traerlo de nuevo a la oficina para entregar

**Comment by jennifervargas** [comment]
Se hace seguimiento y toda la información quedo QAP
