### ISSUE TITLE
PORTAL SAN CARLOS - GLORIA GALVIS

### ISSUE THREAD

**Issue by jsoporte** [soportepctecnologia/PCTecnologiaSAS#112]
No enciende equipo

**Comment by dsoportepc** [comment]
Equipo Lenovo SN°  MP1A825V es trasladado a las instalaciones de lenovo por motivos de garantía bajo la orden de Servicio N°C80-DG208990 ingresado el 4 de diciembre del 2018, el cual a la fecha de hoy en la pagina de consultas de estado del equipo ( https://www.puntodeservicios.com/ ) ingresando con el numero de c.c del ingeniero Alexander Diaz y la orden de servicio nos dice que se encuentra asignado a un técnico, dado esto se espera a que en la pagina el estado cambie a listo para entregar para acercarse a las instalaciones donde fue llevado el equipo.

**Comment by dsoportepc** [comment]
24/12/2018
Se revisa el estado del equipo el equipo en el portal de Lenovo el cual se encuentra en estado control de calidad.

**Comment by soportepctecnologia** [comment]
26/12/2018
Equipo continua en control de calidad

**Comment by dsoportepc** [comment]
29/12/2018 
El equipo se encuentra listo para entregar acercarse al lugar donde se dejo el equipo para reclamarlo.

**Comment by dsoportepc** [comment]
03/01/2019
El equipo se reclama de punto servicios S.A se encuentra en la oficina esperando a que la señor Gloria Galvis vuelva de vacaciones para dar entrega respectiva.
El informe de los técnicos de punto servicios S.A da por ende que al desensamblar el equipo se encuentra que una conexión con un leve desajuste se realizan los ajustes necesarios pasando a pruebas de cámara, usb, microfono, vídeo dando por dañado el cable converter (LCD) se realiza el cambio respectivo y nuevamente a pruebas sin reportar anomalías.

**Comment by dsoportepc** [comment]
14/01/2019
Se da entrega al equipo a la Sra. Gloria Galvis el dia jueves 10/01/2019 realizando instalación de office, antivirus, backup e impresoras.
