### ISSUE TITLE
Toshiba Morenos Portos

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#115]
22-12-2018
TOSHIBA NB505-SP0115OL
sr:6B287985K
Inicia cargando el sistema operativo efectúa un error 0xc000000f "error al seleccionar el arranque, no se puede tener acceso a un dispositivo requerido"
Ingresa con batería y cargador

**Comment by hsoporte** [comment]
Equipo tiene dañado el disco duro, pendiente confirmar con el señor Eduardo Peña si autoriza el cambio de disco.

**Comment by dsoportepc** [comment]
Se realiza la compra de disco duro y se reinstala el sistema operativo junto con sus programas estandar.
