### ISSUE TITLE
INEMFLEX - EQUIPO DE ESCRITORIO DELL

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#117]
Ingresa equipo para revision debido a que no carga el sistema operativo, el equipo se diagnostico en sitio, sin embargo, el problema probablemente es físicamente del disco duro, hacer diagnostico detallado.

**Comment by dsoportepc** [comment]
14/01/2019
Se hace un diagnostico del disco duro dando por ende que la parte afectada se procede a realizar su respectivo cambio y haciendo re instalación del sistema operativo, office, antivirus y qsm. Dando entrega del equipo el dia jueves 10/01/2014.
