### ISSUE TITLE
DIMAP - PORTATIL DELL

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#118]
Ingresa equipo portátil DELL con dos cargadores, uno dañado y otro nuevo, el cargador nuevo presentaba problemas de compatibilidad y no cargaba. se debe realizar cambio del cargador con el proveedor, pendiente gestion de Jhon Jairo con el cambio.

**Comment by dsoportepc** [comment]
14/01/2019
Se realiza el cambio respectivo del cargador y se da entrega del mismo el dia jueves 10/01/2019
