### ISSUE TITLE
Laboratorio - Sign Line - Disco Duro 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#12]
El disco fue llevado a nuestra central de recuperacion de informacion

**Comment by soportepctecnologia** [comment]
Se envió correo electrónico a Duvan sobre la recuperación de la información, estamos a la espera de la decisión de Sign Line

**Comment by jennifervargas** [comment]
El cliente no autoriza el proceso, se trae al laboratorio para hacer la entrega

**Comment by jennifervargas** [comment]
El disco duro es entregado al cliente final
