### ISSUE TITLE
SKL - REPACION PC

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#121]
el dia miercoles 23 de enero ingresa quipo de escritorio marca elux, sin serial visible no inicia sistema operativo sin accesorios

**Comment by hsoporte** [comment]
Ingresa equipo de escritorio para reinstalacion del sistema, sin embargo, se diagnostica problemas en la board por el ing Jesus,, pendiente confirmar reemplazo de la board, debido a que ese equipo empezo a fallar posterior a los mantenimientos fisicos.

**Comment by dsoportepc** [comment]
Se realiza reparación de board, se encuentra falla en disco duro se remplaza es entregado a la compañía
