### ISSUE TITLE
INSTRUMENTACION - SERVIDORES

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#122]
Ingresan dos servidores para realizar las siguientes actividades:

1. Mantenimiento preventivo
2. Reinstalacion del sistema
3. Parametrizacion del sistemas e instalación de programas pertinentes (Antivirus, actualizaciones, etc).

Actualmente lo tiene asignado el ingeniero Jesus

**Comment by dsoportepc** [comment]
1. Se realiza mantenimiento preventivo 
2. Se realiza reinstalacion del sistema operativo 
3. Se realiza parametrizacion del equipo
