### ISSUE TITLE
ANGELA MALDONADO - PORTATIL

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#127]
Ingresa equipo portatil Gateway con cargador y forro para reinstalacion del sistema y reparacion del teclado porque hace falta la tecla ctrl derecho. 

observaciones: Pantalla rayada y carcaza rayada.

Telefono de contacto: 3182145442 Angela Maldonado
judithms63@hotmail.com

**Comment by dsoportepc** [comment]
14/02/2019
Se realiza formateo del equipo por parte del ingeniero Esteban, tecla no se consigue listo para entregar

**Comment by dsoportepc** [comment]
Se realiza la reinstalaron de Sistema operativo y se entrega al cliente, no se encuentra la tecla faltante pero el usuario desea llevarlo sin tecla.
