### ISSUE TITLE
Visita Morenos - Migración de correo electrónico Carolina Correa

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#13]
Se realiza el proceso de migración del correo electrónico donde se traslada los correos electrónicos archivados y se implementa la configuración POP con la opción de guardar durante una semana, Esta pendiente hacer la eliminación del usuario Carolina Correa, desde el equipo que actualmente tienen la gerente de mercadeo (Macbook Air), esto es con el fin de confirmar que todo se traslado al nuevo equipo.

**Comment by sebastiandelgadopc** [comment]
Se realiza seguimiento y el equipo funciona con normalidad.
