### ISSUE TITLE
Instrumentacion - Revision Telefono IP

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#141]
Revisar telefono IP Grandstream GXP1400 S/N 0B30D el cual queda con direccion IP aparentemente fija en otro segmento.

El Telefono ingresa con adaptador de corriente sin cable de red

**Comment by soportepctecnologia** [comment]
![WhatsApp Image 2019-03-29 at 3 21 50 PM(1)](https://user-images.githubusercontent.com/32307016/55260482-91d6dd00-5236-11e9-98bc-8ffd1099ebf5.jpeg)
![WhatsApp Image 2019-03-29 at 3 21 50 PM](https://user-images.githubusercontent.com/32307016/55260485-91d6dd00-5236-11e9-9800-b69198e60395.jpeg)
![WhatsApp Image 2019-03-29 at 3 21 51 PM(1)](https://user-images.githubusercontent.com/32307016/55260486-91d6dd00-5236-11e9-8aad-795a05a83350.jpeg)
![WhatsApp Image 2019-03-29 at 3 21 51 PM](https://user-images.githubusercontent.com/32307016/55260487-926f7380-5236-11e9-859e-443cecfdc12d.jpeg)

**Comment by johansoporte** [comment]
El dispositivo esta listo para entregar, se configura para que quede funcional en Instrumentacion S.A

**Comment by dsoportepc** [comment]
Se asigna ip fija, se actualiza firewall. El equipo es entregado a la compañía
