### ISSUE TITLE
CONSULTORIA Y CONTROL SAS - INGRESO DE EQUIPOS

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#142]
Histórico ingreso de equipos:
1. Se ingresan 10 equipos los cuales se les realizo backup en el disco externo.
2. Se entregan 8 equipos al cliente.
3. Se ingresan 4 equipos los cuales se les realizo backup en el disco externo.
4 Quedan 6 equipos por entregar al cliente, 4  listos y dos con pendientes.

Adjunto evidencia ( Los dos equipos sin empapelar son los que tienen pendientes)

**Comment by johansoporte** [comment]
![1](https://user-images.githubusercontent.com/48966704/55263565-74f2d780-523f-11e9-9b58-8b105d9e3c26.jpeg)
![2](https://user-images.githubusercontent.com/48966704/55263566-758b6e00-523f-11e9-888a-4194af5f607e.jpg)
![3](https://user-images.githubusercontent.com/48966704/55263567-758b6e00-523f-11e9-8d9a-6663f2995083.jpg)
![Uploading 4.jpg…]()
![Uploading 5.jpg…]()
![Uploading 6.jpg…]()

**Comment by johansoporte** [comment]
Queda pendiente la revisión de los portátiles con falla de pantalla con el compañero Rafael el dia de hoy

**Comment by johansoporte** [comment]
El ing Rafael ya reviso los portatiles y efectivamente es falla de pantallas, los equipos pertencen al Sr Zamir Vargas y al Sr. Humberto Gutierrez.
Queda pendiente para realizar el cambio y solicitud de esas pantallas.

**Comment by dsoportepc** [comment]
Se realiza cambio de pantalla a solicitud de creo que se cambio ingeniero Johan
