### ISSUE TITLE
FABIO LEON (MILENTA II) - EQUIPO NO ARRANCA SO

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#143]
Usuario reporta que el equipo se cayo y no enciende el so, se valida y el equipo queda en logo de LENOVO
![1](https://user-images.githubusercontent.com/48966704/55264385-2a268f00-5242-11e9-8c4e-8db939730b6e.jpeg)
![2](https://user-images.githubusercontent.com/48966704/55264386-2a268f00-5242-11e9-8568-ca6ece03ca79.jpg)
![3](https://user-images.githubusercontent.com/48966704/55264387-2a268f00-5242-11e9-850f-c0754a292bff.jpg)
![4](https://user-images.githubusercontent.com/48966704/55264389-2a268f00-5242-11e9-9fd4-a7ee77426ea1.jpg)

**Comment by johansoporte** [comment]
Al iniciar el equipo se detecta daño en el disco duro

**Comment by johansoporte** [comment]
Se realiza cotizacio de disco duro para poder informarle al usurio

**Comment by johansoporte** [comment]
Se esa intentado recuperar la información del disco afectado.

**Comment by dsoportepc** [comment]
Se realiza cambio de disco duro y se instala sistema operativo y se paso de información
