### ISSUE TITLE
MORENOS PORTOS - REPOTENCIACION SERVIDOR

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#145]
HP proliant mg350 g6 
s/n : mxq20904cc se debe realizar upgrade de so a windows server 2019 y reponciacion de segundo procesador y aumento de 32 gb de ram, se debe realizar backup general y se debe programar con la Sra.Arley de meco tell: 3103391173 la instalacion del mismo.

**Comment by johansoporte** [comment]
Se realizo instalacion de dos mudolos de 16gb cada uno para un total de 32gb; el servidor tenia 46gb, de memoria y actualmente quedo con 78gb de memoria.

**Comment by johansoporte** [comment]
Se realiza instalación de procesador Intel Xeon r5645 de 2.4GHZ, actualmente en pruebas.

**Comment by johansoporte** [comment]
Se realiza instalacion de SO windows server 2019 OLP y se realiza contacto con la Ing.Arley de meco para la reinstalacion del Software meco

**Comment by johansoporte** [comment]
Se solicita numero para una futura llamada con HP.

**Comment by dsoportepc** [comment]
Se realiza entrega de servidor de a la compañia
