### ISSUE TITLE
Babylon - Equipo se apaga

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#146]
El equipo se apaga solo, desde que se present
![1](https://user-images.githubusercontent.com/48966704/55557880-78a7b380-56b0-11e9-91c1-444d947195c7.jpg)
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()

o una falla de energia en las instalaciones.

**Comment by johansoporte** [comment]
El equipo se apaga solo, desde que se presento una falla de energia en las instalaciones de babylon

**Comment by johansoporte** [comment]
pendiente revision

**Comment by johansoporte** [comment]
LLega portatil nuevo para pasar backup del equipo con falla
![7](https://user-images.githubusercontent.com/48966704/55592773-2d68c180-56ff-11e9-8cc8-e4a15e73dd31.jpg)

**Comment by johansoporte** [comment]
se extrae información de la particion lenovo y del perfil del usuario y queda en el nuevo equipo

**Comment by dsoportepc** [comment]
Se determina fallo físico por corto, el equipo es reemplazado por uno nuevo
