### ISSUE TITLE
Babylon - Disco duro torre

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#147]
Ingresa disco duro para extraer información.
![4](https://user-images.githubusercontent.com/48966704/55559299-87439a00-56b3-11e9-9629-6bab475a5003.jpg)
![5](https://user-images.githubusercontent.com/48966704/55559306-8b6fb780-56b3-11e9-82ed-bb6d82a703bf.jpg)

**Comment by dsoportepc** [comment]
Disco duro es reemplazado se realiza instalación de sistema operativo office antivirus, programa de paqueadero y facturación
