### ISSUE TITLE
TRANSPORTAR - EQUIPO CON FALLAS DE SO

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#148]
Llega al laboratorio equipo con fallas de sistema operativo 

![1](https://user-images.githubusercontent.com/48966704/55589983-55542700-56f7-11e9-94d2-847a303c7b42.jpg)
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()

**Comment by johansoporte** [comment]
Se extrae backup en el disco negro.Se pasa info de C y del perfil del usuario.

**Comment by dsoportepc** [comment]
Equipo se restablece de fabrica, se instala office y antivirus

**Comment by jennifervargas** [comment]
El equipo se entrega en las instalaciones de Transportar 08/05/2019.
