### ISSUE TITLE
Luz Matiz - equipo lenovo info

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#149]
LLega equipo al laboratorio por perdida de informacion
![1](https://user-images.githubusercontent.com/48966704/55593100-4d4cb500-5700-11e9-861b-eb224c9296b4.jpg)
![2](https://user-images.githubusercontent.com/48966704/55593101-4d4cb500-5700-11e9-97c5-ac6fcb19d8bd.jpg)

**Comment by dsoportepc** [comment]
Equipo en proceso de recuperación de información recuba

**Comment by soportepctecnologia** [comment]
Se realizo recuperacion mediante recuva, se debe informar al cliente para revision

**Comment by soportepctecnologia** [comment]
Datos de Contacto
+57 320 3861661

**Comment by soportepctecnologia** [comment]
Hable con la Sra. Luz Matiz y va viajando, quedamos en hablar sobre las 4 pm

**Comment by wualtersoporte** [comment]
Se recupera información por el software  de  recuva ,  se formatea  dejando  el  backup recuperado sin novedad
