### ISSUE TITLE
Laboratorio - Servidor Morenos

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#15]
El dia Jueves 5 de Octubre se hizo pruebas de funcionamiento, el cual presenta lentitud y bloqueos, el sistema operativo se congela y debe ser apagado para que el sistema funcione nuevamente, NO se realizo pruebas con las 4 GB de memoria RAM, debido a que se pensaba que el servidor se apagaba a causa de la velocidad de las memorias. Actualmente las 2 memorias restantes las tiene Jennifer Vargas.

**Comment by soportepctecnologia** [comment]
Servidor queda en laboratorio de PC Tecnologia
No hacer nada mas
