### ISSUE TITLE
Prefabricados Modulares - Dispositivo de Vigilancia

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#150]
Ingresa dispositivo de seguridad de grabación con su cable de fuente, para reinciar y dejarlo funcional. 
![1](https://user-images.githubusercontent.com/48966704/55653821-4af86280-57b5-11e9-93f2-28554341a869.jpg)
![2](https://user-images.githubusercontent.com/48966704/55653822-4af86280-57b5-11e9-8cc7-5843f42e0456.jpg)

**Comment by dsoportepc** [comment]
Se remplaza dispositivo por uno nuevo
