### ISSUE TITLE
Personal Julian - Equipo para garantia

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#152]
Ingresa equipo HP modelo 14-ck0011la para garantia
![1](https://user-images.githubusercontent.com/48966704/56925163-48c3b400-6a94-11e9-9920-feba83bdd2ac.jpg)
![2](https://user-images.githubusercontent.com/48966704/56925164-48c3b400-6a94-11e9-8acd-5644cdadcf8a.jpg)
![3](https://user-images.githubusercontent.com/48966704/56925165-48c3b400-6a94-11e9-9a5a-e3f198e94462.jpg)
![4](https://user-images.githubusercontent.com/48966704/56925166-495c4a80-6a94-11e9-8e00-c0fbb465c7da.jpg)

**Comment by wualtersoporte** [comment]
Entra  por garantía , directamente por  el fabricante hacen el cambio  del bus de datos  del disco duro a la board quedando operativo sin  novedad
