### ISSUE TITLE
Transintercargo - Servidor por problemas

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#153]
Ingresa al laboratorio servidor por posible amenaza de virus, adicional ingresa su NAS, dos discos duros de backups y licencia de office y w server
![1](https://user-images.githubusercontent.com/48966704/57251580-cb59ef80-700f-11e9-95c9-45c22ea7ab7b.jpg)
![2](https://user-images.githubusercontent.com/48966704/57251581-cb59ef80-700f-11e9-908f-f27ccf546143.jpg)

**Comment by dsoportepc** [comment]
El servidor se restablecen instantáneas, se formatea el equipo y es instalado en las instalaciones de la compañía
