### ISSUE TITLE
TRANSINTERGARGO - EQUIPO NO  DA VÍDEO 

### ISSUE THREAD

**Issue by wualtersoporte** [soportepctecnologia/PCTecnologiaSAS#156]
El equipo presenta falla en  el puerto serial al momento de realizar limpieza sucede el  daño

![WhatsApp Image 2019-06-08 at 9 56 30 AM(1)](https://user-images.githubusercontent.com/50724402/59149005-7c6bf500-89d5-11e9-9894-61c1ad5988b7.jpeg)
![WhatsApp Image 2019-06-08 at 9 56 30 AM(2)](https://user-images.githubusercontent.com/50724402/59149007-85f55d00-89d5-11e9-858f-bed2475846e8.jpeg)
![WhatsApp Image 2019-06-08 at 9 56 30 AM](https://user-images.githubusercontent.com/50724402/59149008-8beb3e00-89d5-11e9-955b-1f39c092207d.jpeg)

Solución 

El  equipo  se  somete a calor para  secar  circuitos del  puerto se  hacen  pruebas  dando  vídeo  sin novedad

**Comment by dsoportepc** [comment]
El equipo es sometido a calor dando vídeo nuevamente el equipo es entregado a la compañía
