### ISSUE TITLE
INSTRUMENTACIÓN-ASESORAMIENTO 

### ISSUE THREAD

**Issue by wualtersoporte** [soportepctecnologia/PCTecnologiaSAS#157]
Solicita asesoramiento del  equipo si  necesita  ya cambio del mismo ya  que  se ha  formateado varias veces funciona  por  un tiempo  estimado  , presenta  lentitud 

![WhatsApp Image 2019-06-08 at 10 29 54 AM](https://user-images.githubusercontent.com/50724402/59149359-074eee80-89da-11e9-8340-73f4844ca352.jpeg)
![WhatsApp Image 2019-06-08 at 10 29 56 AM(1)](https://user-images.githubusercontent.com/50724402/59149361-074eee80-89da-11e9-9692-d8e07e97e9e4.jpeg)
![WhatsApp Image 2019-06-08 at 10 29 56 AM](https://user-images.githubusercontent.com/50724402/59149362-074eee80-89da-11e9-9bc6-b5a35f539790.jpeg)
![WhatsApp Image 2019-06-08 at 10 29 49 AM](https://user-images.githubusercontent.com/50724402/59149363-074eee80-89da-11e9-97d1-15fe55f65c0e.jpeg)

**Comment by dsoportepc** [comment]
Se determina fallo en el disco, se realiza cambio de disco duro se instala sistema operativo, pendiente en punto realizar instalación de office según licencias que se encuentran en instrumentación. Se realiza instalación de antivirus.
