### ISSUE TITLE
Dimap Lenovo ext chia 

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#163]
El equipo ingresa por lentitud en el administrador de tarea se presenta el disco en 100%.
Realiza analisis de disco para descartar daño en el mismo.
![WhatsApp Image 2019-06-29 at 10 18 49 AM](https://user-images.githubusercontent.com/45851431/60386573-406c0300-9a5c-11e9-8840-01a4fbe8f7bd.jpeg)
![WhatsApp Image 2019-06-29 at 10 19 32 AM](https://user-images.githubusercontent.com/45851431/60386574-406c0300-9a5c-11e9-8a72-d43eda149608.jpeg)
![WhatsApp Image 2019-06-29 at 10 18 32 AM](https://user-images.githubusercontent.com/45851431/60386575-406c0300-9a5c-11e9-9669-33f962648f98.jpeg)

**Comment by juancamilopc** [comment]
se realiza mesa de ayuda de equipo lenovo de jenny gonzales el cual presentaba anuncios en el navegador.

se restablece el navegador para que no salgan mas ese tipo de notificaciones.

![WhatsApp Image 2019-09-03 at 8 45 03 AM](https://user-images.githubusercontent.com/54682487/64210449-ec6d0880-ce68-11e9-8846-2f495d4be37b.jpeg)
