### ISSUE TITLE
INSTRUMETACION-BACK UP-CRM Y ERP

### ISSUE THREAD

**Issue by juancamilopc** [soportepctecnologia/PCTecnologiaSAS#169]

**Comment by juancamilopc** [comment]
se realiza Back-Up del servidor CRM y ERP queda en la ruta compartida SIESA Back Ups Nombrado con la fecha actual del 4 de septiembre 2019

![WhatsApp Image 2019-09-04 at 8 48 17 AM (1)](https://user-images.githubusercontent.com/54682487/64260604-c68b4680-cef0-11e9-9ccb-dc53eec7516f.jpeg)
![WhatsApp Image 2019-09-04 at 8 48 17 AM](https://user-images.githubusercontent.com/54682487/64260605-c723dd00-cef0-11e9-961c-025cde90d858.jpeg)

**Comment by johansoporte** [comment]
se realiza Back-Up del servidor CRM y ERP queda en la ruta compartida SIESA Back Ups Nombrado con la fecha actual del 21-09-2019

**Comment by soportepctecnologia** [comment]
ESTA TAREA SE HACE A DIARIO

**Comment by juancamilopc** [comment]
se realiza Back-Up del servidor CRM y ERP queda en la ruta compartida SIESA Back Ups Nombrado con la fecha actual del 21-10-2019
