### ISSUE TITLE
Laboratorio - CPU - Notaria Ibagué 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#17]
Ingresa maquina para revisión general problema de video y analizar posibilidad de ampliar memoria RAM

**Comment by soportepctecnologia** [comment]
Se realizo mantenimiento preventivo
Se instalo modulo de memoria RAM DDR3 1333 de 4 GB Kingston para pruebas

**Comment by jennifervargas** [comment]
La memoria funciona correctamente y se hace el envio a la Notaria

**Comment by soportepctecnologia** [comment]
CPU enviada, se instalo 4 GB de RAM, se deja en inventario modulo de 2GB
