### ISSUE TITLE
Visita Pater - Instalar monitor, teclado y mouse en servidor

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#18]
Según conversación con la Sra. Andrea se llego a la conclusión de instalar un monitor, un teclado y un mouse al servidor para que el soporte remoto se mas fácil

**Comment by hsoporte** [comment]
Tarea Pendiente debido a que surgio un soporte de emergencia con la empresa Agencia de aduana lideres y no se logro finalizar las actividades programadas, pendiente reagendar la visita para culminar el soporte.

**Comment by jennifervargas** [comment]
Visita queda asignada para el lunes 23 en la franja horaria de la mañana

**Comment by hsoporte** [comment]
Se realiza el ajuste del cableado y la instalacion del monitor con teclado y mouse para el servidor, sin embargo esta pendiente por parte de cascos pater la compra del adaptador de corriente del monitos LG debido a que no lo encontraron.
