### ISSUE TITLE
MESA DE AYUDA  - INSTRUMENTACION  - FERNANDO ROMERO

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#183]
POR SOLICITUD DE YESICA SUAREZ DE TACTICA REQUIERE ACCESO COMO ADMINISTRADOR LOCAL

**Comment by soportepctecnologia** [comment]
SE DIO USUARIO .\pctec Y CLAVE ABCde123 PARA QUE TACTICA PUDIERA INSTALAR

**Comment by juancamilopc** [comment]
equipo presenta fallas con la actualización de seguridad, se des-instala y se configura fecha para el programa táctica
