### ISSUE TITLE
MESA DE AYUDA-VELUQUE-BACK UP SERVIDOR

### ISSUE THREAD

**Issue by juancamilopc** [soportepctecnologia/PCTecnologiaSAS#189]

**Comment by juancamilopc** [comment]
Se realiza BKP de servidor veluque 
![WhatsApp Image 2019-09-05 at 8 11 05 AM](https://user-images.githubusercontent.com/54682487/64344841-dff5c680-cfb4-11e9-943e-1474f9369a43.jpeg)

**Comment by juancamilopc** [comment]
Se realiza BKP de servidor veluque con fecha 11-09-2019

**Comment by johansoporte** [comment]
Se realiza BKP de servidor veluque con fecha 16-09-2019

**Comment by juancamilopc** [comment]
Se realiza BKP de servidor veluque con fecha 18-09-2019

**Comment by johansoporte** [comment]
Se realiza BKP de servidor veluque con fecha 21-09-2019

**Comment by juancamilopc** [comment]
Se realiza BKP de servidor veluque con fecha 24-09-2019

**Comment by juancamilopc** [comment]
Se realiza BKP de servidor veluque con fecha 21-10-2019
