### ISSUE TITLE
Laboratorio - Morenos ASUS Fabio

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#19]
El equipo se llevo a garantia , sin em,bargo alli no encontraron nada anomalo
Se trae equipo a laboratorio y se insala windows 10 pro, se actualiza, se instaln aplicativos y drivers

**Comment by soportepctecnologia** [comment]
Se realizo instalacion de windows 10 Pro
Se instalaron Drivers, actualizacion y parques
Se migro Backup y se deja en pruebas

**Comment by soportepctecnologia** [comment]
Se realiza seguimiento con el Sr. Fabio Gomez quien da reporte positivo

**Comment by soportepctecnologia** [comment]
Hoy se realizo instalacion de meco de la mano de deysi, ingeniera de Softland
Se deja en pruebas 
Se debe realizar seguimiento en 1 semana para cierre de caso

**Comment by jennifervargas** [comment]
El Ing. Alexander Diaz hace seguimiento del equipo entregado directamente con el usuario Fabio Gómez, refiere que esta totalmente operativo y no presenta ninguna falla.
