### ISSUE TITLE
MESA DE AYUDA - TRANSINTERCARGO - ACTUALIZAR CHROME KAREN

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#198]
Equipo solicita permisos de administrador para actualizar chrome, de dan los permisos y se valida con el usuario que quede actualizado.

Responsable: Johan Rojas

**Comment by dsoportepc** [comment]
de dan los permisos y se valida con el usuario que quede actualizado.
