### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - VPN Y TACTICA EN MEDELLIN

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#199]
Equipo del Sr Oscar de medellin sin solar y conexión al srv.

Se instala solar, se configura sesión para que ingrese al srv, se mapea carpeta R de tactica, se valida que tiene error 5 en tactica, se repara error 5 de tactica desinstalando actulizacion de seguridad.
Se valida con el usuario que quede operativo el tactica.

Responsable Johan Rojas.

**Comment by dsoportepc** [comment]
Se instala solar, se configura sesión para que ingrese al srv, se mapea carpeta R de tactica, se valida que tiene error 5 en tactica, se repara error 5 de tactica desinstalando actulizacion de seguridad.
Se valida con el usuario que quede operativo el tactica.
