### ISSUE TITLE
Laboratorio - Inemflex - Portátil 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#20]
Ingresa equipo Portátil HP Pavilion x 360 convertible nuevo para configuracion

**Comment by soportepctecnologia** [comment]
Se realizo instalacion de sistema operativo, office, antivirus, parametros de red
Pruebas ok

**Comment by soportepctecnologia** [comment]
Se solicito medio fisico de recuperacion del sistema operativo en HP
Numero de Caso 5004540591

**Comment by jennifervargas** [comment]
El equipo se entrego a don Giovanni Mora, con las configuraciones instaladas junto con la licencia
