### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - CREDENCIALES DR RAFAEL

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#200]
El sr Rafael reporta que no tiene ingreso al srv desde su equipo mac.
Se le indican credenciales de administrador para que tenga acceso y se deja marcada la casilla para recordar las crendenciales.
Se valida con el usuario que tenga acceso al srv, tener en cuenta que  este equipo no tiene solar instalador.

Responsable : Johan Rojas.

**Comment by dsoportepc** [comment]
Se valida con el usuario que tenga acceso al srv, tener en cuenta que este equipo no tiene solar instalador.
