### ISSUE TITLE
MESA DE AYUDA - MORENOS - YERALDIN CONFIGURACION CORREO

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#205]
Usuario solicita optimizar el pst de su correo.
Se ayuda a validar que los correos se encuentren divididos en el nuevo pst y uno de consulta, adicional se deja el nuevo como predeterminado.
(pst de consulta queda guardado en la carpeta de documentos)

Responsable: Johan Rojas.

**Comment by dsoportepc** [comment]
e ayuda a validar que los correos se encuentren divididos en el nuevo pst y uno de consulta, adicional se deja el nuevo como predeterminado.
(pst de consulta queda guardado en la carpeta de documentos)
