### ISSUE TITLE
MESA DE AYUDA - ARFLINA - CONFIGURACION ARCHIVOS DE PRECIOS

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#207]
Sede de santa ana reporta que se le daño el archivo de precios.
Se vuelve a configurar el archivo y se valida con el usuario que quede operativo.

**Comment by dsoportepc** [comment]
Se vuelve a configurar el archivo y se valida con el usuario que quede operativo.
