### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - TATIANA ERROR 5 TACTICA

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#208]
Usuario reporta error 5 en tactica.
Se desinstala actulizacion de seguridad que ´genera este error.
Se reinicia equipo y se deja dicha actulizacion desactiva.

**Comment by dsoportepc** [comment]
Se desinstala actulizacion de seguridad que ´genera este error.
Se reinicia equipo y se deja dicha actulizacion desactiva.
