### ISSUE TITLE
Laboratorio - SKL - Instalar Equipo Nuevo

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#21]
Ingresa equipo para configurar y entregar

**Comment by soportepctecnologia** [comment]
Se realizo instalacion de Windows 10 Pro, sin embargo el product key que viene impreso esta incompleto, por lo tanto se reporto caso en Microsoft y enviaron el codigo completo asi: DQBGD-NBDPD-TYQWM-4C8RG-3V66P

**Comment by hsoporte** [comment]
El equipo fue enviado terminado de instalar y enviado a SKL para configurarlo con la red de la empresa.

**Comment by soportepctecnologia** [comment]
Se creo usuario asiscomercial en AD
