### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - Permisos carpetas de red

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#210]
1.
UNIDAD EN EL SERVIDOR:   aa ho aa productos y precios (\\192.168.7.149)
Unicos usuarios con permiso de escritura:  FBRAVO
Unicos usuarios con permiso de solo lectura:  SACOSTA, AMOJICA, JPEDRAZA, PLOPEZ, CSOLARTE, DVARELA
2.

UNIDAD EN EL SERVIDOR:  aa dx productos y precios (\\192.168.7.149)
Unicos usuarios con permiso de escritura:  FBRAVO, BMARTIN
Unicos usuarios con permiso de solo lectura:  SACOSTA, AMOJICA, JPEDRAZA, PLOPEZ, CSOLARTE, DVARELA
con solo LECTURA en ambas unidades tambien incluir a LCERON

Usuario solicita estos permisos para las carpetas de red, los permisos quedan tal cual se solicitaron.

**Comment by dsoportepc** [comment]
Usuario solicita estos permisos para las carpetas de red, los permisos quedan tal cual se solicitaron.
