### ISSUE TITLE
MESA DE AYUDA - Instrumentacion - Lucia Ceron 

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#212]
La usuaria se comunica por que al encender el equipo no encuentra los archivos del pc 
El equipo presenta un error de windows al cargar los usuarios por lo cual se restablecen carpetas a punto de restauración de días 8/09/21:45, se extrae un la información de un disco duro externo.

El equipo no deja modificar perfil por regedit y se realiza restablecimiento de equipo a como se encuentra el dea 1/9/2019

**Comment by dsoportepc** [comment]
Equipo no responde al restablecimiento por lo cual se solicita un pc de préstamo a instrumentación para realizar configuración y poder hacer revisión del equipo en laboratorio

**Comment by dsoportepc** [comment]
Se realiza configuración de equipo de préstamo y enviado a instrumentación

**Comment by juancamilopc** [comment]
se realiza soporte al equipo de la señora lucia ceron donde no podia ingresar al usuario creado para ella, el motivo por el cual no podia era que el teclado estaba desactivado, se realizan unas pruebas junto con el usuario por medio de llamada telefonica, logrando solucionar la novedad presentada
