### ISSUE TITLE
MESA DE AYUDA - DIMAP - AUDITORIA ANTIOQUIA

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#213]
AUDITORIA DIMAP ANTIOQUIA

**Comment by soportepctecnologia** [comment]
SE CREO LINK EN DRIVE https://docs.google.com/document/d/1El1b_B74E6PNcRg7Cx2pTw9-SPJ6_0LVQylNKqP243c/edit#

**Comment by soportepctecnologia** [comment]
YA SE REALIZO AUDITORIA 4 EQUIPOS EN LA UNION

**Comment by juancamilopc** [comment]
se llama la Sra Soly Ruiz para finalizar auditoria de equipos, pero me informa que no es posible realizar el día de hoy la auditoria, me comentan que se encuentran en capacitaciones y procesos que requieren de los equipos los cuales necesitan usar y me dice que es difícil seguir el proceso, por lo tanto me manifiesta que el día sábado se comunica para coordinar el tema para finalizar dicha auditoria

**Comment by juancamilopc** [comment]
me comunico a la sede san pedro pero no contestan para formalizar la auditoria

**Comment by juancamilopc** [comment]
se realiza informe de dimap hasta donde se ha realizado avances de los equipos se envia a correo personal de ingeniero alexander

**Comment by juancamilopc** [comment]
el dia de hoy me comunico con la señora soly ruiz de la sede entrerrios para finalizar la auditoria de los equipos, con la novedad que no se puede finalizar el dia de hoy debido que los equipos son portatiles y salieron a campo muy temprano, ella queda de comunicarse una ves los tenga dentro de la sede

**Comment by juancamilopc** [comment]
se realiza el día de hoy contacto con las personas que hacen falta para el informe de DIMAP con el fin de finalizar lo mas pronto por lo que se tiene la siguiente novedad:

el señor Juan Montoya ya nos dejo realizar por su parte el informe del equipo
la señora Aurora Escobar a las 3:30 pm se realiza conexión
el señor Jairo Ortega el día de mañana a las 9 am
el señor Jorge Londoño hasta el día miércoles

lo cual se daría por terminado el día miércoles en la tarde si algo extraordinario no ocurre

**Comment by juancamilopc** [comment]
se actualiza informe de equipos auditoria dimap, con novedad que falta un equipo para finalizar el cual sera atendido el día de mañana para así realizar entrega
