### ISSUE TITLE
MESA DE AYUDA - Petropalma - No puedo ingresar a perse 

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#214]
El usuario se encontraba sin internet ya que soporte tecnico de internet hizo la conexion mal siendo un error de capa 8. El usuario ya tiene uso de internet y acceso a perse

**Comment by soportepctecnologia** [comment]
El usuario se encontraba sin internet ya que soporte tecnico de internet hizo la conexion mal siendo un error de capa 8. El usuario ya tiene uso de internet y acceso a perse
