### ISSUE TITLE
Laboratorio - Acrópolis Portatil Don Fernando 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#23]
Equipo ingresa para revisión, no prende

**Comment by hsoporte** [comment]
Se revisa el equipo al cual se desinstala el service pack 1 de Win 7 y ha funcionado bien. sin embargo fue necesario tambien desinstalar el antivirus. Actualmente esta pendiente hacer mas pruebas de funcionamiento para confirmar que no se apague.

**Comment by jennifervargas** [comment]
Se hace entrega del equipo, ya que compraron uno nuevo para cambiarlo, se pasa la información en la visita del 30 de Octubre a cargo de el Ing. Hassan Marquez

**Comment by hsoporte** [comment]
Debido a la capacidad y limitaciones del equipo se realizo el cambio por un nuevo equipo y se configura con la configuración de red y programas pertinentes.
