### ISSUE TITLE
Visita Contrato Inemflex 24/Oct/17

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#24]
1. El portatil de German Mora no instala correctamente el office 2016, la clave es: D4N3R-29MJC-P7MD8-J444V-G6PMK y como este equipo no tiene unidad de DVD, esta almacenado el ejecutable en c/soporte
2. El equipo de victor no tiene KAS
3. El equipo de Claudia ayer presento daño de pst, se dejo ejecutando herramienta scanpst; el equipo de claudia es el servidor de NOVASOFT, este equipo no tiene ningun nivel de seguridad, yo ya he solicitado con claudia la migracion de novasoft al servidor, sin embargo esto aun no se ha concretado.
4. el equipo de nurian del 1 piso , se desconecta cada rato, el problema es de red, NO ES RESPONSABILIDAD DE PC, eso es con Diego, sin embargo quiero dejar constancia por escrito de esto y en conocimiento de Giovani

**Comment by hsoporte** [comment]
1. Se realiza la reinstalacion del equipo del señor German Mora, se configuran los programas pertinentes y el office con la licencia mencionada, tambien se hace la configuracion del correo y accesos al servidor.

2. Se hace la instalacion de la licencia de antivirus KAS en el equipo de Victor.

3. Se indica a Claudia la necesidad del traslado de Novasoft al servidor y se deja por escrito en la orden de servicio.

4. Se indica el inconveniente con el cableado del area de control de calidad y se plantea la opcion de cambiar el cableado para enviar la propuesta.
