### ISSUE TITLE
MESA DE AYUDA - MORENOS -  EQUIPO LENOVO FORMATEAR

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#246]
Equipo entra por lentitud
Se deja backup en D
Se instala w8.1 pro
Equipo entra sin cargador.

**Comment by johansoporte** [comment]
![1](https://user-images.githubusercontent.com/48966704/64823720-cee12280-d57d-11e9-8737-354932982eae.jpg)
![2](https://user-images.githubusercontent.com/48966704/64823722-cf79b900-d57d-11e9-98a4-8344edbdcb16.jpg)
![3](https://user-images.githubusercontent.com/48966704/64823725-d0124f80-d57d-11e9-80e6-789193c9cd25.jpg)
![4](https://user-images.githubusercontent.com/48966704/64823726-d0aae600-d57d-11e9-8496-ea4c7cbc97a9.jpg)

**Comment by johansoporte** [comment]
Equipo queda todo ok a nvl de software queda pendiente licencia de windows

**Comment by johansoporte** [comment]
Equipo queda en oficina para que lo repare físicamente el ing rafale.

**Comment by johansoporte** [comment]
![1](https://user-images.githubusercontent.com/48966704/65344514-850bc400-db9d-11e9-9b95-4aff21148f22.jpg)
![2](https://user-images.githubusercontent.com/48966704/65344517-863cf100-db9d-11e9-9eac-261114e3bf43.jpg)

**Comment by johansoporte** [comment]
El ingeniero Rafael informa en el diagnositco que es necesario reparar una bisagra y las partes plasticas de la pantalla que se encuentran dañadas.

**Comment by johansoporte** [comment]
![tr1](https://user-images.githubusercontent.com/48966704/65773167-58a5f980-e101-11e9-8d49-f927fd8f94da.jpg)

**Comment by johansoporte** [comment]
Se repara visagra por parte del ing rafael

**Comment by johansoporte** [comment]
Se cambia teclado por uno nuevo

**Comment by johansoporte** [comment]
Se instalan apps base y queda listo para entregar

**Comment by johansoporte** [comment]
Equipo sale para la sede de morenos todo OK.

**Comment by soportepctecnologia** [comment]
Claudia Lugo Cartagena
