### ISSUE TITLE
Laboratorio - Portátil Jhon Jairo Diaz

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#25]
Ingresa al laboratorio Portátil Samsung NP300, no prende (arranca pero no da video)

**Comment by jennifervargas** [comment]
Rafael revisa el equipo pero o arranca, refiere que el equipo ya ha sido destapado, que faltan algunos tornillos, se lo lleva a su laboratorio.

**Comment by jennifervargas** [comment]
Se realiza cambio de BIOS a la board, se pasa el costo al cliente para su autorizacion

**Comment by hsoporte** [comment]
El equipo se repara, funciona correctamente, fue entregado a Jhon Jairo.
