### ISSUE TITLE
MESA DE AYUDA - ARFLINA - CLAVE WIFI ARFLINA SANTA ANA

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#255]
YOLANDA SOLICITA CLAVE WIFI SANTA ANA

**Comment by johansoporte** [comment]
![image](https://user-images.githubusercontent.com/48966704/64896922-25fefa00-d647-11e9-9fc5-bf8226fd2f70.png)

**Comment by johansoporte** [comment]
Se extrae del repositorio de pc los siguientes datos
Red Wi-fi
Usuario: Arflina106
Contraseña: %ARFLINA106%
