### ISSUE TITLE
MESA DE AYUDA - DIMAP - ENTRERRIOS - SOLY NO PUEDE IMPRIMIR SIIGO

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#257]
Buenas tardes, me ayudan por favor no he me esta dejando imprimir una copia de una factura
![WhatsApp Image 2019-09-13 at 3 44 26 PM](https://user-images.githubusercontent.com/32307016/64894301-f0eea980-d63e-11e9-80dd-9c679447c72f.jpeg)

**Comment by soportepctecnologia** [comment]
SE DEBE ESCALAR TEMA A SIIGO

**Comment by dsoportepc** [comment]
Se realiza instalación a siigo y se realiza la configuración e la misma
