### ISSUE TITLE
Visita Contrato Morenos Rosal

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#26]
1. Revisar camaras (DVR) ya que no estan disponibles via web, confirmar con eduardo peña

**Comment by soportepctecnologia** [comment]
Asignado al Ing. Hassan Marquez

**Comment by hsoporte** [comment]
Se realiza la visita de soporte en la cual hace backup y mantenimiento preventivo a todos los equipos, adicionalmente se hace mantenimiento a las impresoras, tanto del area de Pos cosecha y planta deshidratados.

Se revisa el inconveniente de las camaras de seguridad y se configura la direccion ip 192.168.2.220 al DVR para hacer el NAT con el router de IP data.

**Comment by juancamilopc** [comment]
Se realiza copia de BKP en servidor de Pc tecnologia de equipos de las empresa kiska morenos sede rosal
