### ISSUE TITLE
MESA DE AYUDA - BITAX - CONFIGURACION IMPRESORA

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#268]
Se solicita configuración de impresoras en la compañia

**Comment by dsoportepc** [comment]
Se realiza configuración de impresora a 4 equipos de la compañía pendiente 1 que no se encuentra en la compañía. bajo la ip 192.168.0.127

**Comment by soportepctecnologia** [comment]
Tiempo empleado hasta el momento 1 Hora

**Comment by dsoportepc** [comment]
La usuaria indica el portátil no se encuentra en la instalaciones y queda programado el día de mañana a las 17 de septiembre del 2019 aproximadamente a las 9:30 am

**Comment by juancamilopc** [comment]
se instala impresora de bitax a equipo portatil el cual no se encontraba en dias anteriores y adicional se instala dropox y se configura para las carpetas que se encuentran en la nube. tiempo de duracion 1 hora y 2 minutos
