### ISSUE TITLE
Inemflex - Cableado Estructurado

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#27]
Nurian del area de calidad tiene inconvenientes con la conexion a internet, el inconveniente se presenta por el estado del cableado, ella comento el caso al ingeniero Alexander y al señor Giovanny Mora para enviar la cotizacion del cambio.

**Comment by Bibianarosas** [comment]
Se hace el arreglo funcional por parte de Rafael Campo, se factura a Inemflex queda en espera de cotización de rafael ya de la parte física y de belleza de la red para hacer la propuesta a Inemflex

**Comment by hsoporte** [comment]
Pendiente autorizacion por el cliente
