### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACIÓN - VPN Derlys Varela  

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#275]
La usuaria indica que sigue sin funcionamiento de carpetas compartidas por VPN

**Comment by dsoportepc** [comment]
Se realiza reinstalación de OPENVPN y configuración de los archivos de correspondientes en el momento que se ejecuta la VPN para realizar pruebas el usuario se queda sin internet.

El usuario queda en conectarse con nosotros para poder realizar la validación del funcionamiento de la VPN

**Comment by juancamilopc** [comment]
se realiza pruebas en laboratorio de pc tecnologia, con la novedad de que la vpn funciona en optimas condiciones

**Comment by soportepctecnologia** [comment]
![image](https://user-images.githubusercontent.com/32307016/65712647-2347d000-e05d-11e9-9745-a64e76e0d00f.png)

**Comment by dsoportepc** [comment]
Se establece comunicacion con la usuaria indicando que estaba ocupada para realizar la configuracion de la VPN

**Comment by dsoportepc** [comment]
Se realiza configuracion de VPN por el cisco RV016 con la IP 181.49.122.162 USUARIO dvarela contraseña ABCde123
