### ISSUE TITLE
Laboratorio - Petropalma - CPU 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#28]
Ingresa equipo para revisión, el cliente refiere que no inicia; Es muy importante hacer Backup.

**Comment by sebastiandelgadopc** [comment]
Se realiza reinstalacion de equipo y restablecimiento de informacion y configuracion. Pendiente realizar activacion de Windows y terminar de instalar actualizaciones

**Comment by hsoporte** [comment]
Se realiza la activación del equipo y se culmina las actualizaciones, el equipo se encuentra listo para entregar.
