### ISSUE TITLE
MESA DE AYUDA - PETROPALMA - ACTIVACION OFFICE

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#284]
La usuaria manifiesta que no puede editar archivos de office

**Comment by dsoportepc** [comment]
Se realiza validación nos encontramos con 2 office instalados desinstalamos office 365 y queda instalado office professional 2013 no licenciado validar licenciamieto del equipo

**Comment by soportepctecnologia** [comment]
SE ENVÍA CORREO REPORTANDO EL OFFICE NO LEGAL A ANA Y A ROBINSON
![Uploading 2019-09-17_15-02-31.jpg…]()
