### ISSUE TITLE
Laboratorio - Abalark Portatil Toshiba (Pedro Gomez)

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#29]
Se debe revisar equipo internamente (Rafael Campo) ya que el usuario manifiesta que le cayo agua con bicarbonato y limón sobre el teclado.

!la información es super importante!

Equipo Toshiba Satellite L505-GS5037 S/N: 4A069257Q
Batería Original Toshiba
Cargador Original Toshiba

ANTES DE CUALQUIER ARREGLO SE DEBE INFORMAR AL CLIENTE.

**Comment by jennifervargas** [comment]
Se diagnostica el equipo y se cotiza el teclado y el cargador al cliente, pero este no autoriza, el equipo se devuelve al cliente.
