### ISSUE TITLE
MESA DE AYUDA - DIMAP- LENTITUD RED

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#299]
Usuario reporta que tiene fallas por lentitud para ingresar al servidor.

**Comment by johansoporte** [comment]
Se valida que el problema es por conexión de red, se pospone actualizaciones de kaspersky y se hace una limpieza de dns en el equipo, se valida con el usuario que quede mas fluida la conexión con el srv.

**Comment by johansoporte** [comment]
Se realiza pruebas con el router y se pierde la red con UNE, se valida con UNE e informan que enviaran un técnico en el transcurso del día.

**Comment by johansoporte** [comment]
Pendiente pruebas por usuario

**Comment by dsoportepc** [comment]
Sin inconvenientes desde el día de la visita
