### ISSUE TITLE
Comercial - Abalark - Cotización de programa Licenciado para edicion de PDF

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#3]
Es necesario cotizar un programa para edición de archivos PDF en el equipo de la arquitecta Norma quien utiliza el portátil Asus de la sede de Ibague, se instalo una versión trial de Nitro PDF, por tanto se debe realizar la instalación final del programa que se va utilizar antes del día **27 de Octubre del 2017**, posteriormente no podrá editar los archivos.

**Comment by hsoporte** [comment]
Sugerencia Adobe Reader Professional

**Comment by Bibianarosas** [comment]
Recibido - En tramite de enviar propuesta

**Comment by Bibianarosas** [comment]
Se envía hoy 3 de Octubre a la sra Rocio Propuesta de Acrobat Suscripción Anual
