### ISSUE TITLE
Laboratorio - Abalark Alistamiento portátil HP

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#30]
Ingresa portatil HP 530 S/N: CND73605BT con bateria original y cargador JAWAN

Se debe realizar alistamiento de equipo para dejarlo con windows, office, antivirus KAS y Autocad

**Comment by sebastiandelgadopc** [comment]
Se realiza activacion de office, reparacion de OS, limpieza con Ccleaner. Se dejan corriendo actualizaciones para proceder con reinicio del sistema e instalacion de antivirus. Pendiente reiniciar y realizar mantenimiento fisico

**Comment by soportepctecnologia** [comment]
Se realiza mantenimiento (limpieza fisica), se programa con rocio la entrega en Abalark el viernes 3 Nov en horas AM

**Comment by soportepctecnologia** [comment]
Se realiza entrega fisica directamente al Arq. Fernando en la DIAN de la Av 68
