### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACIÓN - FALLA IMPRESIÓN A COLOR 

### ISSUE THREAD

**Issue by jsoporte** [soportepctecnologia/PCTecnologiaSAS#308]
El usuario Eucarin, reporta problemas para imprimir a color.

**Comment by soportepctecnologia** [comment]
EL SEÑOR EUCARIN MORALES NECESITABA IMPRIMIR A COLOR EN LA IMPRESORA RICOH 3003, LA CUAL ESTABA EN LA IP 192.168.7.252

SE CONFIGURO IMPRESORA TANTO EN EL EQUIPO DE EL COMO EN EL SERVIDOR PARA QUE PUDIERA IMPRIMIR EN SIESA

**Comment by soportepctecnologia** [comment]
![Uploading 1.jpg…]()
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()
![Uploading 4.jpg…]()

**Comment by soportepctecnologia** [comment]
![1](https://user-images.githubusercontent.com/32307016/65341377-d912aa80-db95-11e9-81eb-2a893daeb9a1.jpg)

![2](https://user-images.githubusercontent.com/32307016/65341460-0eb79380-db96-11e9-88ec-8230b87ccc23.jpg)


![3](https://user-images.githubusercontent.com/32307016/65341687-84bbfa80-db96-11e9-8b98-b4a436c77c98.jpg)

![4](https://user-images.githubusercontent.com/32307016/65341699-8e456280-db96-11e9-9c8d-9cf185fd9c88.jpg)
