### ISSUE TITLE
Laboratorio - Acrópolis - Portatil 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#31]
Ingresa equipo nuevo para alistar y entregar

**Comment by Bibianarosas** [comment]
Se entrega del área comercial Equipo Lenovo Touch Corei3 - para configuración a nombre de María paula Piedrahíta hoyos, Equipo con Office No Legal, por favor instalar antivirus con clave Z8Z9E-V1ANK-8VBAJ-NS7YA.

**Comment by soportepctecnologia** [comment]
*Se realiza instalación de KAS versión de prueba porque la clave asignada por comercial no sirvió
* Se actualiza windows
* Se instala Google, winrar
* Office

**Comment by soportepctecnologia** [comment]
Se realiza entrega física en las instalaciones de Acrópolis
