### ISSUE TITLE
MESA DE AYUDA-LABORATORIO-PC JANUS NUEVO LINE CARGO

### ISSUE THREAD

**Issue by juancamilopc** [soportepctecnologia/PCTecnologiaSAS#332]

**Comment by juancamilopc** [comment]
se realiza instalacion de sistema operativo, paquete de office, antivirus, adobe, winrar y driver de nuevo equipo para line cargo

serial equipo 190821487908
board msi h310m pro vdh plus 
intel core i5 9400 f 2.9 GHz
1 tera de disco
memoria ram de 8 Gb DDR4 2666MHz
fuente de poder de 300 W
chasis janus c175

donde se traslada informacion de anterior disco el cual dejo de funcionar equipo de area comercial

se salva informacion de particion c y particion d y queda alamacenada en disco c carpeta soporte tecnico

**Comment by johansoporte** [comment]
Queda pendiente driver 3.0 y validar que no tengan pendientes, queda asignado a la mesa de ayuda

**Comment by dsoportepc** [comment]
Se realiza instalación del equipo en sitio a cargo del ingeniero Juan Camilo
