### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - PERMISOS ALMACEN

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#340]
![image](https://user-images.githubusercontent.com/32307016/65712412-9866d580-e05c-11e9-8f05-f09d1acc4d25.png)

**Comment by dsoportepc** [comment]
![image](https://user-images.githubusercontent.com/45851431/65719937-83923e00-e06c-11e9-8b24-d8494ddda721.png)

Se habilitan permiso para galbarracin como lectura y escritura según solicitud
