### ISSUE TITLE
MESA DE AYUDA - LIDERES - EXTENSIÓN 114 NO FUNCIONA

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#344]
EXTENSIÓN 114 NO FUNCIONA

**Comment by johansoporte** [comment]
Se realizan pruebas y se validan que la falla es en el cable de red que va del teléfono a la pared, se hacen pruebas con otro cable y son exitosas, se le informa al usuario que debe solicitar el cambio del cable de red para evitar esta intermitencia con la ext
