### ISSUE TITLE
MESA DE AYUDA - TRANSINTERCARGO - SOLICITUD DE CREDENCIALES

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#362]
Karen informa que el equipo de la Sra Daissy solicita credenciales siempre para poder ingresar al srv

**Comment by johansoporte** [comment]
Pendiente validar con el usuario

**Comment by soportepctecnologia** [comment]
Me contacte pero el usuario no esta, dejar abierto caso, ellos se contactan

**Comment by dsoportepc** [comment]
Se ingresa dns del srv 192.168.1.100 y ip publica 190.157.8.33 como dns favoritos
