### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - MATRIZ DE PERMISOS HASSAN

### ISSUE THREAD

**Issue by dsoportepc** [soportepctecnologia/PCTecnologiaSAS#366]
Don German Rey solicita el acceso a carpeta isoaño de lectura y escritura para el usuario Hassan y lectura para iso9000 
![image](https://user-images.githubusercontent.com/45851431/65795354-b0f3f000-e12f-11e9-9e87-1f81103c9315.png)

**Comment by dsoportepc** [comment]
Se otorgan permisos de lectura y escritura para el usuario cartera en la carpeta isoaño

**Comment by soportepctecnologia** [comment]
![image](https://user-images.githubusercontent.com/32307016/65798286-e3551b80-e136-11e9-97ca-1fbd8ce29722.png)
