### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - CONCEDER PERMISO RW  CARPETA ISOAÑO 

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#369]
![image](https://user-images.githubusercontent.com/32307016/65802064-2ff12480-e140-11e9-868a-042f3f4d4f90.png)

**Comment by dsoportepc** [comment]
Se dan permisos de lectura y escritura a pdiaz el usuario cartera ya se le habían dando permiso para esta carpeta el dia de hoy en el caso #366
