### ISSUE TITLE
Remoto - Transportar cargo - Internet en el servidor

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#37]
El equipo servidor no tienen acceso a internet, se dan instrucciones telefonicas pero no se logra restablecer, el problema es unicamente en el servidor, queda pendiente debido a que la señora Angela Toca no tenia disponibilidad de tiempo.

**Comment by jennifervargas** [comment]
Se asigna visita de soporte para revisar el tema en la visita del 16/11/2017

**Comment by hsoporte** [comment]
Se realiza la visita de soporte donde se revisa el inconvenientes y se corrige por medio de la asignacion de una ip publica al servidor. Se realizan pruebas y funciona correctamente.
