### ISSUE TITLE
MESA DE AYUDA - INSTRUMENTACION - PERMISOS DE CARPETA

### ISSUE THREAD

**Issue by johansoporte** [soportepctecnologia/PCTecnologiaSAS#375]
Se otorgan los siguentes permisos 

Pf 
Marcela Cardozo, 
AB PORTAFOLIO, 
Lectura habilitada

y  se valida con el usuario.

**Comment by dsoportepc** [comment]
Se realiza confirmacion con el usuario quedando con acceso a las carpetas respectivamente
