### ISSUE TITLE
Laboratorio - Cesar Buitrago Diaz

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#38]
Ingresa equipo HP Elite Book 6930p
S/N: 2CE0201CDK
Con Bateria
Sin Cargador

Problema: El equipo se afecto con el derramamiento de un liquido; el equipo no se ha prendido desde el suceso

**Comment by soportepctecnologia** [comment]
Equipo es retirado por Rafael Campo

**Comment by jennifervargas** [comment]
Rafael determino, que el equipo tiene problemas irreparables con la Board y el Chip de Video, se programa devolución al laboratorio.

**Comment by hsoporte** [comment]
Se le informa al señor Cesar acerca del estado del equipo y adicionalmente se extrae la informacion del disco duro externo por el Ingeniero Sebastian. Se le informa al señor Cesar para que traiga un disco duro extraible y pasar la informacion o una galleta para dejarlo como disco portable.
Pendiente cotizar portatil de segunda.

**Comment by hsoporte** [comment]
Pendiente que el señor Cesar Buitrago recoja el backup del equipo para cerrar el caso.

**Comment by jennifervargas** [comment]
Se entrega la información completa al cliente.
