### ISSUE TITLE
Laboratorio - Transintercargo - Servidor 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#39]
Ingresa equipo para revisión

**Comment by soportepctecnologia** [comment]
El servidor presenta daño de Board

**Comment by jennifervargas** [comment]
Se revisa la board y se determina que esta en corto, Rafael se lleva la maquina para su laboratorio.

**Comment by Bibianarosas** [comment]
Se Cotiza Board Nueva y fue aprobada la entregan entre miércoles y viernes 24 de Noviembre, a Transintercargo se les dio de 11 a 12 días hábiles de entrega

**Comment by hsoporte** [comment]
Se realiza instalacion de la misma y se entrega servidor funcionando correctamente
