### ISSUE TITLE
Laboratorio - Revision Equipo Daniel Cabrera

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#4]
21 de Septiembre de 2017

Este equipo ingreso inicialmente por Pantalla Azul al encenderlo y el equipo no iniciaba, se intento ejecutar el recovery para dejarlo de fabrica y casi al finalizar el proceso se "reventaba" nuevamente y volvia a sacar pantalla azul.

22 de Septiembre de 2017

Se procedió a reemplazar el disco duro (previo backup) y se instalo version Windows 10 OLP, se instalaron todos los programas, se reestablecio backup y "aparentemente" se habia superado el problema.

23 de Septiembre de 2017

El usuario manifiesta que el equipo nuevamente presenta "pantalla azul"

27 de Septiembre 2017

El equipo reingresa a Laboratorio por el mismo problema (pantalla azul y no inicia), este servicio inicialmente se asigna a Rafael Campo

**Comment by jennifervargas** [comment]
El equipo fue revisado por Rafael Campo, le realizo limpieza, cambio de pasta termica, y ajusto el procesador, se estan realizando pruebas para entregarlo.

**Comment by jennifervargas** [comment]
Se realizan pruebas, el equipo termino todas las actualizaciones, y esta listo para entregar

**Comment by soportepctecnologia** [comment]
Acabe de hablar con Daniel Cabrera y pasa el dia de hoy (29 de Sep) sobre las 3 PM, esto es una garantia por lo tanto no genera costo
