### ISSUE TITLE
Laboratorio - Admon. MILENTA II - Monitor 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#40]
Ingresa monitor, administración de Milenta, el cliente refiere que no enciende.

**Comment by jennifervargas** [comment]
Asignado a Rafael Campo, lo revisara el miércoles 15, en la franja horaria de la mañana

**Comment by jennifervargas** [comment]
Rafel realiza la configuración del monitor, se hacen pruebas y queda funcionando correctamente, se notifica al cliente para que pase por el.

**Comment by hsoporte** [comment]
Fue realizado un mantenimiento al equipo por el ingeniero Alexander, se realizaron pruebas de funcionamiento, el equipos se encuentra listo para entregar.
