### ISSUE TITLE
CASCOS PATER - INSTALACION ROUTER

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#43]
Se realiza la instalacion de un router Trendnet N300 para corregir errores de lentitud, el inconveniente radicaba en el router anterior (D-LINK) el cual permitia ser configurado, pero la velocidad de internet y acceso al servidor se disminuia considerablemente, fue reseteado y reconfigurado varias vece, sin embargo, no funciono por lo cual se tomo la desicion del cambio. 
Dispositivo se dejara en pruebas para corroborar el funcionamiento antes de ser facturado.

**Comment by jennifervargas** [comment]
Se realiza seguimiento en Router funciona con normalidad y se factura al cliente.
