### ISSUE TITLE
MESA DE AYUDA - INEMFLEX - ALISTAMIENTO "SERVIDOR" PRESTAMO PARA KSC

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#438]
PC TECNOLOGIA EN VISTA DE LOS INCONVENIENTES OCASIONADOS POSTERIOR A LA IMPLEMENTACION DE KASPERSKY ENDPOINT CON EL SOFTWARE QSM - NOVASOFT Y CARPETAS COMPARTIDAS, TOMO LA DECISION DE PRESTAR UN EQUIPO "SERVIDOR" PARA INSTALAR EN EL LA CONSOLA DE ADMINISTRACION KSC 11

**Comment by juancamilopc** [comment]
el equipo presenta fallas de reinicio por lo tanto queda evidenciado que :

El servidor de kas presenta fallas de reinicio por lo tanto se le da instrucciones a la señora ibi que en caso de que se deba reiniciar se debe hacer un procedimiento para que nuevamente el servidor de kaspersky suba sin inconvenientes

Se debe verificar que el servidor este comunicandose con la tarjeta de red asi que debe estar parpadeando las luces del puerto pci 
Si no es asi 
Se debe apagar el boton de la fuente volver a prender el boton y encender la cpu comun y corriente lo cual debe arrojar nuevamente que los leds de la tarjeta pci esten encendidos y en comunicacion
