### ISSUE TITLE
LABORATORIO - JAIME CASTRO - CPU

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#44]
Ingresa CPU HP se debe reinstalar con WIN 10 (si es posible) el cliente olvido la clave de ingreso, realizar mantenimiento correctivo y preventivo

**Comment by hsoporte** [comment]
Se realiza la reinstalacion del equipo de computo con sistema operativo Windows 7 y los programas pértinentes para su funcionamiento, no se realiza backup.
Equipo listo para entregar

**Comment by jennifervargas** [comment]
El cliente pasa a recoger el equipo el lunes 18 Dic, a la oficina

**Comment by jennifervargas** [comment]
El equipo se entregó a satisfacción al cliente.
