### ISSUE TITLE
LABORATORIO - JAIME CASTRO - PORTATIL COMPAQ 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#45]
Ingresa Portátil se debe reinstalar con WIN 10 (si es posible), realizar mantenimiento correctivo y preventivo revisar antivirus, la pantalla presenta pixeles quebrados. 

Clave de Ingreso: techrona

**Comment by hsoporte** [comment]
Se realiza la reinstalacion del equipo de computo con sistema operativo Windows 7 y los programas pértinentes para su funcionamiento, no se realiza backup.
Equipo listo para entregar

**Comment by jennifervargas** [comment]
El cliente pasa a recoger el equipo el lunes 18 Dic, a la oficina

**Comment by jennifervargas** [comment]
El equipo se entregó a satisfacción al cliente.
