### ISSUE TITLE
LABORATORIO - PORTATIL SAMSUMG - FACTORY SRA PAOLA 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#48]
Ingresa equipo para revisión por parte de Rafael, parece que la batería explotó.

**Comment by jennifervargas** [comment]
Rafael entrega equipo en funcionamiento, tiene problemas de lentitud se lo entrega a Sebastián para que lo revise internamente.

**Comment by jennifervargas** [comment]
El equipo esta en proceso de reinstalación.

**Comment by hsoporte** [comment]
Se realiza la instalación de los programas, el equipo fue reinstalado con el recovery por el ingeniero Sebastian Delgado, se revisa el sistema y queda funcionando OK, el equipo tiene la bateria dañana, por el momento funciona conectado directamente a la correiente.

Pendiente cotizar y confirmar con el cliente si se realiza el cambio de la bateria o se deja en el estado que esta. En el caso de no ser autorizado el cambio el computador se puede entregar.

**Comment by jennifervargas** [comment]
Equipo es entregado por el Ing Alexander, en las instalaciones de Factory
