### ISSUE TITLE
LABORATORIO - PORTATIL DELL - WILLIAM MILENTA

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#49]
Ingresa equipo sin cargador para arrelgar boton lateral del encendido debido a que lo dejaron caer y se rompio. En cliente acordó traer el cargador para que podamos hacer las pruebas una vez este arreglado.

EQUIPO DELL PP39L.

**Comment by jennifervargas** [comment]
El equipo es asignado para que lo revise Rafael Campo, ya que el daño es fisico.

**Comment by jennifervargas** [comment]
El equipo lo diagnostico Rafael, se pide autorización con el cliente para reparar el boton, y hacer mantenimiento al equipo

**Comment by jennifervargas** [comment]
El equipo fue reinstalado se detecta un problema con el mouse del equipo, se estan cotizando la pieza para ver si podemos reemplazarla

**Comment by jennifervargas** [comment]
Se hacen pruebas, la pieza no se puede reemplazar, se recomienda trabajar el equipo con Mouse adiconal, se alistar para entregar.

**Comment by hsoporte** [comment]
Se realiza el alistamiento del equipo, se hace mantenimiento preventivo del sistema y se confirma que funcione el boton de encendido correctamente. Equipo listo para entregar.

**Comment by jennifervargas** [comment]
Bibiana Rosas, realiza la entrega del equipo.
