### ISSUE TITLE
LABORATORIO - VELUQUE - EQUIPO 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#52]
Ingresa Disco Duro Externo ADATA HD710 con cable. 
AIO LENOVO C-Series, blanco con cargador, teclado (original) y mouse (genérico). 
Impresora Samsung ML2165W, con cables de la impresora de red y de poder.

**Comment by jennifervargas** [comment]
1. Computador Lenovo: no carga el sistema

2. Impresora esta fallando la impresion

3. El conector del cable del disco se esta desprendiendo es asegurarlo

**Comment by jennifervargas** [comment]
Rafael revisa la impresora, detecta la board esta dañada, se pasa a proceso de cotización.

**Comment by hsoporte** [comment]
1. El disco duro sera entregado nuevamente a Veluque, no se realiza reparacion para no asumir responsabilidades de daño, se recomienda reemplazo a Johanna y Claudia Sanchez, el disco fue retirado por Hassan Amin para entregar.

2. Pendiente autorizacion de cambio de disco duro del equipo DELL All In One de Villavicencio.

3. Pendiente revision de la tarjeta logica de la impresora reemplazada por Rafael.

**Comment by sebastiandelgadopc** [comment]
Se realiza cambio de disco duro de equipo Lenovo AIO y se reinstala sistema operativo dejándolo operativo con sus debidas aplicaciones, es enviado para Jaimor junto con el disco duro retirado del mismo

**Comment by jennifervargas** [comment]
Los equipos se entregaron en las instalaciones de Veluque Bogota
