### ISSUE TITLE
LABORATORIO - SR. NELSON 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#55]
Ingresan portátiles:
** HP PAVILION DV6000, para revisión general, ingresa con cargador, bateria y sin disco duro 
**TOSHIBA SATELLITE M645-54080, con bateria y cargador, para revisión general.

**Comment by sebastiandelgadopc** [comment]
Se realiza revisión pertinente de los equipos y se encuentra:
TOSHIBA:
Este equipo no cuenta con adaptador de corriente, no tiene ni memorias ni disco duro y todos sus tornillos no están presentes por ende esta sin ajustar

HP:
El equipo ingresa sin disco duro sin embargo el equipo prende. Este si cuenta con memorias ram y adaptador electrico

**Comment by jennifervargas** [comment]
En el Laboratorio, diagnostican que los equipos no tienen arreglo, son preparados para entregar al cliente.
