### ISSUE TITLE
LABORATORIO - SOBRE RUEDAS - PORTATILES 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#57]
Ingresan portátiles SAMSUNG 905S Y 530V, para revision general, cambio de batería y licencia de antivirus.

**Comment by sebastiandelgadopc** [comment]
se realiza revision general de los equipos, se evidencia daño en las baterias de ambos  y en el wifi del samsung 905s se procede a revisar  y la antena del wifi estaba desconectada, se realizan actualizaciones a la ultima version de windows 10 en el samsung 530v y en el samsung 905s se generan las correspondietnes actualizacion del sistema operativo tambien mantenimiento general de los equipos y quedan al dia.
