### ISSUE TITLE
LABORATORIO - INEMFLEX - FUENTE DE PODER 

### ISSUE THREAD

**Issue by jennifervargas** [soportepctecnologia/PCTecnologiaSAS#61]
Ingresan fuentes de poder para revisión de Rafael, al parecer estan quemadas.

**Comment by jennifervargas** [comment]
Fuente se diagnostica y no se puede reparar en laboratorio.

**Comment by hsoporte** [comment]
Se realiza la entrega de la fuente de poder a la mensajeria de Inemflex, equipo entregado y se cierra el caso.
