### ISSUE TITLE
Laboratorio Alejandra Gonzalez - Equipo no enciende y reinstalar sistema

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#62]
Ingresa equipo para backup y reinstalacion, actualmente el equipo no enciende, revisar si es necesario hacer algun cambio de hardware.

**Comment by nsoporte** [comment]
se verifica el equipo y se concluye que el disco duro esta dañado, se reemplaza por un disco duro de una tera y se instala todo el sistema operativo y aplicaciones basicas, el quipo queda a punto.
