### ISSUE TITLE
Laboratorio Wilder Chaparro, mantenimiento y revision pc de mesa y portatil

### ISSUE THREAD

**Issue by nsoporte** [soportepctecnologia/PCTecnologiaSAS#63]
revisión de los equipos y verificación de la posibilidad de re potenciar e instalar adaptador wifi para cpu de escritorio.

**Comment by nsoporte** [comment]
se optimizan los dos equipos, se instala el adaptador wifi en el equipo de mesa queda totalmente funcional ,se realiza mantenimiento fisico de ambos equipos, se instalan complementos y se activa office y windows del pc portatil.

**Comment by soportepctecnologia** [comment]
Se realiza entrega a satisfaccion.
