### ISSUE TITLE
LABORATORIO - GARANTIA TRANSINTERCARGO

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#67]
Equipo fue tramitado por garantia con Compumax en donde hicieron cambio de fuente de poder. llega al laboratorio para hacer pruebas de funcionamiento.

**Comment by nsoporte** [comment]
se realiza entrega del equipo a trasintercargo debido a que en las pruebas que se realizaron en el laboratorio funciono correctamente.

**Comment by nsoporte** [comment]
compumax realiza cambio de la fuente de poder y entrega el equipo a pc tecnología, donde se le realizan pruebas y funciona correctamente, por lo que se le entrega a transintercargo.
