### ISSUE TITLE
MORENOS - DISCO DURO PORTATIL

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#69]
Ingresa disco duro extraible ADATA para hacer recuperación de información debido a que el formato de lectura esta dañado, lo que se debe hacer es intentar recuperar la información con recuva u otro programa de recuperación básico. Cualquier informacion adicional confirmar con Sebastian.

**Comment by sebastiandelgadopc** [comment]
Disco perteneciente al Dr Roberto Moreno, el cual se le recupera información y se formatea. Se entrega disco personalmente
