### ISSUE TITLE
Laboratorio - Cascos Pater

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#7]
El quipo HP 205 All in one SN: 4CE42112QH Product N°: E3T81L el cual tiene la pantalla dañada, es necesario reemplazarla, de modo que se debe llevar al laboratorio  de PC Tecnologia.

Se debe cotizar la pantalla y confirmar a la señora Maria Paternina para autorizacion.

Actualmente el equipo se encuentra en la sede del 7 de Agosto.

**Comment by Bibianarosas** [comment]
Vale Hassan, Gracias. Ya me encargo

**Comment by hsoporte** [comment]
Lo intente revisar en la sede pater para confirmar la referencia exacta de la pantalla, pero es mejor hacerlo desde el laboratorio para desarmarlo completamente.

**Comment by Bibianarosas** [comment]
El dia de hoy desde Pater traen el equipo a laboratorio para cotizar pantalla para cambio
