### ISSUE TITLE
CPU clon Carlos Pinilla

### ISSUE THREAD

**Issue by nsoporte** [soportepctecnologia/PCTecnologiaSAS#71]
se recibe cpu para revisión ya que no enciende y cuando lo hace se apaga.

**Comment by nsoporte** [comment]
se realizo verificación del equipo y se identifico que la board esta dañada, se procede a hacer mantenimiento general del equipo y a montar otra board, montando el equipo mecánicamente desde cero, se realizan pruebas y funciona correctamente.

**Comment by soportepctecnologia** [comment]
Se entrega equipo
Pruebas OK
