### ISSUE TITLE
Overhaul Portátil Samsung N145 Plus

### ISSUE THREAD

**Issue by nsoporte** [soportepctecnologia/PCTecnologiaSAS#75]
se recibe portatil samsung mini, para realizar mantenimiento y revisión general, no funciona correctamente el teclado al oprimir una tecla presenta errores, hay que reparar o cambiar el teclado.

**Comment by hsoporte** [comment]
Se realiza entrega del equipo, se prueba funcionamiento y se firma acta de entrega.
