### ISSUE TITLE
ABALARK - Asus Garantia

### ISSUE THREAD

**Issue by nsoporte** [soportepctecnologia/PCTecnologiaSAS#78]
Se recibe pc portatil asus para tramitar garantía, por lentitud parece problema de procesamiento.

**Comment by jennifervargas** [comment]
Se entrega equipo para realizar proceso de garantía

**Comment by hsoporte** [comment]
Equipo se encuentra en laboratorio, pendiente instalar programas pertinentes:
Office 2010 no Licenciado
Autocad Licenciado (Los datos de la licencia están en el portal en la parte de recursos web)
Winrar
Nitro PDF
Adobe reader
Kaspersky Small Security con Licencia

**Comment by nsoporte** [comment]
Se realiza instalación de programas después de traer el equipo de la garantía se prueba y funciona correctamente, se envía a Ibague y manifiestan que funciona de la manera correcta(queda pendiente si deciden comprar licencia de office)

**Comment by soportepctecnologia** [comment]
Se entrego equipo pruebas OK
