### ISSUE TITLE
Laboratorio - Liceo San Carlos de Cajica

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#8]
Realizar revisión Disco Duro

**Comment by jennifervargas** [comment]
Disco Duro, es enviado a nuestra central de recuperacion de informacion

**Comment by soportepctecnologia** [comment]
Se dio aval en iRecovery para la recuperacion en camara limpia

**Comment by soportepctecnologia** [comment]
Se realiza entrega física de la información en el liceo en cajica

**Comment by jennifervargas** [comment]
Se hace seguimiento de la entrega y el proceso fue exitoso. Se cierra el caso
