### ISSUE TITLE
GALLETAS DANNES - LABORATORIO

### ISSUE THREAD

**Issue by nsoporte** [soportepctecnologia/PCTecnologiaSAS#83]
Ingresa equipo debido a que no esta dando video, es necesario revisarlo y confirmar si se puede arrglar, consultar el costo del arreglo antes de hacerlo con el señor Wilson Galezo.

**Comment by soportepctecnologia** [comment]
Problema con el Chip de video
NO SE RECOMIENDA ARREGLAR
se debe entregar cuando tengamos alguna vuelta cerca

**Comment by jennifervargas** [comment]
El equipo se entrega, sin autorización de arreglo, el día 13 de agosto de 2018.
