### ISSUE TITLE
Portatiles Irma Rodriguez

### ISSUE THREAD

**Issue by nsoporte** [soportepctecnologia/PCTecnologiaSAS#85]
Se reciben 3 portátiles de marca Toshiba Satellite L645-S4102 , Lenovo S110 , Lenovo Ideapad 320 con sus respectivos cargadoresy baterias para realizar su revision.

**Comment by hsoporte** [comment]
Equipo Toshiba se ajusto todo el sistema, pendiente hacer mantenimiento preventivo y confirmar a la señora Irma que algunas teclas del lado izquierdo estan fallando, por lo tanto lo recomendable es utilizar teclado externo.

Portatil Lenovo mini, se descarta cualquier reparacion, se encuentra listo para entregar.

**Comment by dsoportepc** [comment]
Equipo entregado
