### ISSUE TITLE
Abalark - Sony Vaio 

### ISSUE THREAD

**Issue by nsoporte** [soportepctecnologia/PCTecnologiaSAS#89]
Se recibe  PC portátil Sony Vaio para formatear y dejar en optimas condiciones.

**Comment by soportepctecnologia** [comment]
Se debe hacer backup de este equipo y enviar a Norma Rubiano para verificacion antes de formatear

**Comment by dsoportepc** [comment]
Se realizo entrega del equipo a Rocio Bautista
