### ISSUE TITLE
Laboratorio - Equipo Reinaldo

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#9]
Cambio de carcasa y revisar si no tuvo daño interno por golpe

**Comment by hsoporte** [comment]
Se realizo cambio de la carcasa y prueba de las piezas para confirmar que no presentara fallas. El equipo quedo funcionando correctamente y se le informa al señor Reinaldo que puede pasar a recogerlo

**Comment by jennifervargas** [comment]
El equipo lo recogió ya el cliente
