### ISSUE TITLE
LICEO SAN CARLOS - Acer escritorio

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#90]
Ingresa equipo para revisión debido a que presenta errores al bootear el sistema, posibles problemas de disco duro.

Ingresa únicamente la torre del equipo.

**Comment by hsoporte** [comment]
Se realiza la revision del equipo el cual presenta fallas fisicas en la board y el disco duro, se notifica a Viviana de Liceo San carlos a quien se notifica que es mejor realizar el cambio por un nuevo equipo, pendiente enviar cotización. Se descarta cualquier reparacion del equipo y se encuentra listo para entregar.

**Comment by soportepctecnologia** [comment]
Se informa a cliente que es mejor reemplazar el equipo, se envio cotizacion

**Comment by soportepctecnologia** [comment]
Se entrego equipo SIN REPARAR
