### ISSUE TITLE
Laboratorio - Portatiles Miguel Cabrera 

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#91]
Se realiza el ajuste del sistema operativo, junto con los programas pertinentes, incluyendo el programa Atlas, el cual muestra un aviso al ingresar acerca del codigo serial de activacion, es totalmente normal, simplemente es cerrar e ingresar. La licencia del office esta pendiente por activar, esto lo realiza directamente el cliente.

**Comment by hsoporte** [comment]
Equipo Toshiba, se encuentra en revision para ajustar MousePad.

**Comment by soportepctecnologia** [comment]
1. Se reinstalo equipo (fabrica) se instalo Atlas TI Version 6 / se instalo office 365 prueba, pendiente activacion / se restauro backup / PENDIENTE REVISAR BACKUP POR PARTE DEL CLIENTE
2. Se soluciono problema de Touchpad, se encontro daño en pin de seguridad CDROM
PENDIENTE REVISAR BACKUP PARA PROCEDER A REINSTALAR

**Comment by hsoporte** [comment]
Equipo Toshiba pendiente por entregar, lo tiene el ingeniero Alexander, junto con el equipo Lenovo que ingreso nuevamente para revision.

**Comment by dsoportepc** [comment]
Equipo entregado
