### ISSUE TITLE
Laboratorio - Milenta 2 Impresora HP Pro M102W

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#93]
Se recibe impresora para revision
Viene con cable USB

**Comment by soportepctecnologia** [comment]
Problema con el Toner
NO se recarga
Se debe cotizar Toner nuevo

**Comment by jennifervargas** [comment]
Impresora se entrega sin ningún soporte realizado, solo se diagnostico el toner por cambio, se cotizo, se devuelve a la administración el 22/08/2018
