### ISSUE TITLE
LICEO SAN CARLOS - PORTATIL LENOVO

### ISSUE THREAD

**Issue by sebastiandelgadopc** [soportepctecnologia/PCTecnologiaSAS#94]
Portátil ingresado por daño de display. Cotizar pantalla y dar informe para autorizar cambio.

Lenovo G405
Modelo: 20239
S/N: CB29368056

**Comment by soportepctecnologia** [comment]
Se cotizo pantalla $ 230.000

**Comment by soportepctecnologia** [comment]
De: Pagaduria Liceo San Carlos <pagadurialsc@gmail.com> 
Enviado el: jueves, 23 de agosto de 2018 02:54 p.m.
Para: Pc Tecnologia - Su Aliado IT <bibianarosas@pc-tecnologia.com>
Asunto: Re: Cambio de pantalla

Buenas tardes

Ingeniero Alexander

Para solicitarle iniciar el proceso de arreglo del monitor, por favor nos confirma cuando este listo para coordinar personal para recogerlo

Mil gracias 

Viviana Rodriguez U.
Pagadora.
Liceo San Carlos de Cajica.
Tel. 8833407 ext 104
Calle 1 N° 8a 23

**Comment by sebastiandelgadopc** [comment]
Se realizo cambio de pantalla.
Equipo listo para la entrega

**Comment by dsoportepc** [comment]
equipo entregado
