### ISSUE TITLE
Laboratorio - Portátil Toshiba Julian Cabrera

### ISSUE THREAD

**Issue by soportepctecnologia** [soportepctecnologia/PCTecnologiaSAS#95]
No inicia sistema operativo

**Comment by soportepctecnologia** [comment]
Equipo ingresa con cargador y bateria.

**Comment by soportepctecnologia** [comment]
Se detecta daño en Disco Duro, Se autoriza cambio por Disco Duro de 1 Tera $ 250.000

**Comment by soportepctecnologia** [comment]
Toshiba Satellete L45-B4201SL
Part No. PSKQYP-00CLM1
WINDOWS 8.1
S/N: 6E04494S

**Comment by hsoporte** [comment]
Se realiza la instalación del disco duro nuevo, junto con el sistema operativo Windows 8.1 Single Language con licencia original activada telefónicamente por Microsoft,

Se realiza la revision del disco duro y no se logro recuperar informacion, la falla es mecanica.

Pendiente instalar programas pertinentes (Office, antivirus, adobe reader...)

El equipo queda operativo para trabajar archivos de ofimaticos y de poco consumo de rendimiento.

**Comment by sebastiandelgadopc** [comment]
Se realiza instalación de programas pendientes y los solicitados por el usuario, se actualiza el sistema operativo. Se realiza entrega al usuario el día 18 de agosto. Deja disco duro para revisión de recuperación de información si llega a ser posible realizarla.
