### ISSUE TITLE
Laboratorio - Canacol

### ISSUE THREAD

**Issue by hsoporte** [soportepctecnologia/PCTecnologiaSAS#96]
Ingresa equipo para hacer el siguiete servicio:

1. Realizar backup de la informacion, el cliente tiene claro que se recupera la informacion pero los programas se pierden.
2. Reinstalar el sistema con Windows XP junto con los programas pertinentes (Office, Adobe reader....)
3.  Revisar quetal funciona con pruebas normales de uso, confirmar si el disco duro luego de reinstalar funciona con normalidad.

Fecha aproximada de entrega dia Martes 21 de Agosto.

**Comment by soportepctecnologia** [comment]
Se dio acceso al contador Alejandro para revisión de información

**Comment by soportepctecnologia** [comment]
Se realizo instalacion de windows XP SP3 descargado de Dropbox y se instalaron aplicativos, se restauro backup pruebas ok

se entrego equipo

**Comment by soportepctecnologia** [comment]
Se realizo verificación con el Sr. Alejandro Garzon de la información
