### ISSUE TITLE
Laboratorio - William Perdomo Agencia de Aduanas

### ISSUE THREAD

**Issue by sebastiandelgadopc** [soportepctecnologia/PCTecnologiaSAS#97]
No prende

**Comment by sebastiandelgadopc** [comment]
Se soluciono corto en chip de encendido y vídeo, se cambiaron unas teclas que estaban dañadas
Equipo listo para la entrega.

**Comment by hsoporte** [comment]
Se tramito garantía del equipo y fue entregado al señor William perdomo.

Servicio finalizado

**Comment by hsoporte** [comment]
Equipo ingresa para revisión nuevamente y actualmente lo tiene Rafael en revision para ajustar el inconveniente de video

**Comment by dsoportepc** [comment]
Equipo ajustado y entregado.
