### ISSUE TITLE
Laboratorio - Andrea Galindo 

### ISSUE THREAD

**Issue by sebastiandelgadopc** [soportepctecnologia/PCTecnologiaSAS#99]
Presenta fallas en el Touch Pad

**Comment by sebastiandelgadopc** [comment]
El equipo tiene problemas de lentitud y al parecer por fallas del disco duro, se hacen pruebas del touch pad y funciona, sin embargo, puede ser falta de mantenimiento. Hacer pruebas físicas del equipo para descartar daños de hardware.

Datos de acceso

Usuario: Andrea
Clave: egypto2013

Usuario: Recursos humanos
Clave: RRHH2017

**Comment by hsoporte** [comment]
Se realiza la revision del equipo el cual presenta inconvenientes con bloqueos del sistema y demoras al encender, inicialmente se diagnostico problema de disco duro, sin embargo, al realizar la pruebas con otro disco presenta las mismas fallas, adicionalmente la bateria esta fallando.
Se hará la revisión con el apoyo de Rafael Ocampo para confirmar con exactitud que falla fisica esta presentando.

**Comment by sebastiandelgadopc** [comment]
Se realiza instalación de drivers, office profesional plus 2016 activado con crack. Adicionalmente se ajusta tarjeta de red inalambrica la cual queda funcionando correctamente. Pendiente revisar estado de la bateria

**Comment by hsoporte** [comment]
Se hace la revisión del equipo y presenta los siguientes inconvenientes físicos:

1. No enciende con la batería conectada.
2. No encienden los led que indican si esta prendido o cargango en la esquina izquierda del portatil.
3. No funciona el puerto USB de la esquina izquierda.

Se le notifico a Jennifer y Rafael para hacer la revision.

Referente al funcionamiento del sistema, se encuentra funcionando con todo los programas instalados.

**Comment by dsoportepc** [comment]
Se realiza entrega del equipo
